### ISSUE TITLE
Minimist dependency

### ISSUE THREAD

**Issue by vzvenyach** [unitedstates/citation#104]
Unless minimist is installed globally, a local installation throws an error.

**Comment by konklone** [comment]
I'm unable to reproduce. I installed citation globally, and was able to execute it. I installed citation locally into a new directory and ran `./node_modules/citation/bin/cite` with some text and that worked fine too. In neither case did I have `minimist` installed locally or globally.

Mind re-opening with a reproducible set of steps?
