### ISSUE TITLE
Does not pickup "571 U.S. ___ (2014)"

### ISSUE THREAD

**Issue by bulltorious** [unitedstates/citation#105]
I am testing this against various opinions and it does not seem to pickup citations that use the "___"..can that be added.  For example, in http://www.supremecourt.gov/opinions/14pdf/14a840_gol1.pdf it finds "548 U. S. 1301 (2006)", but not "571 U. S. ___ (2014)".

**Comment by adelevie** [comment]
Thanks for reporting this! Care to write a failing test for this? No worries if not :)
