### ISSUE TITLE
Does not recognize "42 U.S.C.285t–2(a)" (with missing space before 285)

### ISSUE THREAD

**Issue by havenl** [unitedstates/citation#122]
In Bills, occasionally there's citation to USC without a space separating `U.S.C.` and the section number (e.g., `42 U.S.C.285t–2(a)` in https://www.congress.gov/bill/114th-congress/house-bill/6/text). This isn't recognized.

**Comment by JoshData** [comment]
This is definitely a drafting error (i.e. very likely to be corrected in a future version of the bill).

(Not saying we shouldn't recognize it.)

**Comment by konklone** [comment]
Thanks to @dustmop for fixing this!
