### ISSUE TITLE
Incomplete section number in '42 U.S.C. 288–1(a)' (with en dash)

### ISSUE THREAD

**Issue by havenl** [unitedstates/citation#123]
Section number after en dash (unicode 8211) isn't recognized. For example, in `42 U.S.C. 288–1(a)` (with en dash), I get 
```JSON
{
  "results": {
    "citations": [
      {
        "type": "usc",
        "match": "42 U.S.C. 247b",
        "index": 0,
        "usc": {
          "title": "42",
          "section": "247b",
          "subsections": [],
          "id": "usc/42/247b"
        }
      }
    ]
  },
  "options": {}
}
```
But with `42 U.S.C. 288-1(a)` (with short dash), I get 
```JSON
{
  "results": {
    "citations": [
      {
        "type": "usc",
        "match": "42 U.S.C. 247b-22",
        "index": 0,
        "usc": {
          "title": "42",
          "section": "247b-22",
          "subsections": [],
          "id": "usc/42/247b-22"
        }
      },
      {
        "type": "usc",
        "match": "42 U.S.C. 247b-22",
        "index": 0,
        "usc": {
          "title": "42",
          "section": "247b",
          "subsections": [],
          "id": "usc/42/247b"
        }
      },
      {
        "type": "usc",
        "match": "42 U.S.C. 247b-22",
        "index": 0,
        "usc": {
          "title": "42",
          "section": "22",
          "subsections": [],
          "id": "usc/42/22"
        }
      }
    ]
  },
  "options": {}
}
```

**Comment by JoshData** [comment]
= #43 (just a reminder to close that one too when we close this one --- this issue is clearer)

**Comment by konklone** [comment]
@havenl Any interest in tackling this issue? #43 has a good discussion of some of the factors involved.

**Comment by havenl** [comment]
So en-dash and hyphen don't have intrinsically different meaning, right? If so, can we not just replace all en-dash with hyphen prior to processing?

**Comment by konklone** [comment]
I wouldn't do a massive find/replace on the whole document, because I don't think we can guarantee they'll always share the same meaning for every citation type. I'd rather extend each relevant regex to match on various hyphen types.

**Comment by JoshData** [comment]
Just on the technical point:

> So en-dash and hyphen don't have intrinsically different meaning, right?

I think they do, but no one actually knows what they are.

**Comment by konklone** [comment]
I also just think it might be reasonable to accommodate how particular corpuses operate, regardless of semantic meaning. As a (fictional, but plausible) example, if GPO's official Statutes at Large used em dashes for ranges, and hyphens for identifiers which involved hyphens somehow -- even if other Statutes at Large collections did not, or if other collections used the opposite notation -- I would want to be able to capture that difference in the regex. 

The citator can accommodate contextual information being passed in. For example, the DC Code regex can be told "I'm giving you a document that is the DC Code itself" and so it can use a regex that doesn't need to see "DC Code" prefixed in front of it, and will interpret bare section identifiers as DC Code citations. Leaving the library any available tools to wrangle citations to the ground helps. =)
