### ISSUE TITLE
Congress sometimes adds dashes

### ISSUE THREAD

**Issue by phearlez** [unitedstates/citation#43]
In h.r.3554 in the 113th Congress (so possibly elsewhere) a reference to USC has a dash in it.

<text>Section 338B(b) of the Public Health Service Act (<external-xref legal-doc="usc" parsable-cite="usc/42/254l-1">42 U.S.C. 254l–1(b)</external-xref>) is amended—</text> 

the parser doesn't recognize the dash and quits without grabbing the (b) portion.

I'm not 100% sure of this use of a dash is appropriate or not - GPO has on occasion even served up invalid XML - but it might be worth accounting for; I'm not yet certain how common it is since we only detect it by human eyeballs.

**Comment by JoshData** [comment]
This is currently failing because it's an en-dash – instead of a regular hyphen. Looks like we need a quick fix at https://github.com/unitedstates/citation/blob/master/citations/usc.js#L54 and https://github.com/unitedstates/citation/blob/master/citations/usc.js#L111.
